### ISSUE TITLE
CSV files missing

### ISSUE THREAD

**Issue by bhakes** [coinmetrics/data#4]
It looks like the bot deleted a massive number of `.csv` files.
![Screenshot 2024-06-18 at 12 19 57 PM](https://github.com/coinmetrics/data/assets/12475863/2c6d153b-6d54-495e-88b2-467215469043)

**Comment by nathanramoscfa** [comment]
Seconded, most of the csv files are now missing.

**Comment by bhakes** [comment]
they are back now... closing this issue

**Comment by nathanramoscfa** [comment]
The issue is happening again today.

**Comment by zrgxbt** [comment]
Happening again, 404 error on btc.csv
